# Generated by Django 4.2.7 on 2025-12-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("total_marks", models.IntegerField(default=0)),
                ("duration_minutes", models.IntegerField()),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "exams",
                "ordering": ["-year", "name"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("order", models.IntegerField()),
                ("max_marks", models.IntegerField(default=20)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "sections",
                "ordering": ["exam", "order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.IntegerField()),
                (
                    "question_text",
                    models.TextField(help_text="Supports LaTeX formatting"),
                ),
                (
                    "plain_text",
                    models.TextField(
                        blank=True, help_text="Plain text version without LaTeX"
                    ),
                ),
                ("option_a", models.CharField(max_length=500)),
                ("option_b", models.CharField(max_length=500)),
                ("option_c", models.CharField(max_length=500)),
                ("option_d", models.CharField(max_length=500)),
                (
                    "correct_option",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                ("marks", models.IntegerField(default=1)),
                (
                    "diagram_url",
                    models.URLField(
                        blank=True, help_text="Optional diagram/image URL", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.section",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["section", "question_number"],
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["is_published"], name="exams_is_publ_8bb3b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["year"], name="exams_year_61f053_idx"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["exam", "order"], name="sections_exam_id_2ab103_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("exam", "order")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["section", "question_number"],
                name="questions_section_775a09_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("section", "question_number")},
        ),
    ]
