# Generated by Django 5.2.8 on 2025-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="solution_video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube URL for complete paper solution video",
                null=True,
            ),
        ),
    ]
