# Generated by Django 5.2.8 on 2025-12-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_exam_solution_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="access_tier",
            field=models.CharField(
                choices=[("FREE", "Free Access"), ("PRO", "Pro Access")],
                db_index=True,
                default="PRO",
                help_text="Minimum tier required to access this exam",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["access_tier"], name="exams_access__46c2cd_idx"),
        ),
    ]
