# Generated by Django 5.2.8 on 2025-12-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_exam_access_tier_exam_exams_access__46c2cd_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="available_from",
            field=models.DateTimeField(
                blank=True, help_text="Exam becomes available from this time", null=True
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="available_until",
            field=models.DateTimeField(
                blank=True, help_text="Exam available until this time", null=True
            ),
        ),
    ]
