# Generated by Django 5.2.8 on 2025-12-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_exam_available_from_exam_available_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject name (e.g., Engineering Mathematics)",
                        max_length=200,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Topic name (e.g., Matrices)", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file_path",
                    models.CharField(
                        help_text="Relative path from notes directory (e.g., engineering_mathematics/matrix_notes.pdf)",
                        max_length=500,
                    ),
                ),
                (
                    "access_tier",
                    models.CharField(
                        choices=[("FREE", "Free"), ("PRO", "PRO Only")],
                        db_index=True,
                        default="FREE",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within subject"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notes",
                "ordering": ["subject", "order", "topic"],
                "indexes": [
                    models.Index(
                        fields=["subject", "is_active"], name="notes_subject_06f609_idx"
                    ),
                    models.Index(
                        fields=["access_tier"], name="notes_access__38844b_idx"
                    ),
                ],
            },
        ),
    ]
