# Generated by Django 5.2.8 on 2025-12-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0005_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="PYQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_name",
                    models.CharField(
                        help_text="Exam name (e.g., DCET, Mock Test 1)", max_length=200
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Year of the exam (e.g., 2023, 2024)"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file_path",
                    models.CharField(
                        help_text="Relative path from pyqs directory", max_length=500
                    ),
                ),
                (
                    "access_tier",
                    models.CharField(
                        choices=[("FREE", "Free"), ("PRO", "PRO Only")],
                        db_index=True,
                        default="FREE",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within year"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pyqs",
                "ordering": ["-year", "order", "exam_name"],
                "indexes": [
                    models.Index(
                        fields=["year", "is_active"], name="pyqs_year_c135d1_idx"
                    ),
                    models.Index(
                        fields=["access_tier"], name="pyqs_access__7084a8_idx"
                    ),
                ],
            },
        ),
    ]
