# Generated by Django 5.2.8 on 2025-12-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0006_pyq"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Topic name (e.g., Matrices, Calculus)",
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(help_text="Video title", max_length=300)),
                ("description", models.TextField(blank=True)),
                ("youtube_url", models.URLField(help_text="YouTube video URL")),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=0, help_text="Video duration in minutes"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within topic"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "video_solutions",
                "ordering": ["topic", "order", "title"],
                "indexes": [
                    models.Index(
                        fields=["topic", "is_active"],
                        name="video_solut_topic_a170eb_idx",
                    )
                ],
            },
        ),
    ]
