# Generated by Django 5.2.8 on 2025-12-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0007_videosolution"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("message", models.TextField()),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("EXAM_DATE", "Exam Date"),
                            ("RESULTS", "Results"),
                            ("URGENT", "Urgent"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "announcements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="announcemen_is_acti_da44f2_idx",
                    )
                ],
            },
        ),
    ]
