# Generated by Django 5.2.8 on 2025-12-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of features included in this plan",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this plan is available for purchase",
            ),
        ),
    ]
