# Generated by Django 5.2.8 on 2025-12-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_alter_payment_status_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider_payment_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
