# Generated by Django 4.2.7 on 2025-11-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_key", models.CharField(max_length=100, unique=True)),
                ("setting_value", models.TextField()),
            ],
            options={
                "verbose_name": "App Setting",
                "verbose_name_plural": "App Settings",
                "db_table": "app_settings",
            },
        ),
    ]
