# Generated by Django 5.2.8 on 2025-12-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_tier",
            field=models.CharField(
                choices=[("FREE", "Free User"), ("PRO", "Pro User")],
                db_index=True,
                default="FREE",
                help_text="User subscription tier",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_tier"], name="users_user_ti_e3e728_idx"),
        ),
    ]
