# Generated by Django 5.2.8 on 2025-12-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_user_tier_user_users_user_ti_e3e728_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, help_text="Admin/staff access"),
        ),
    ]
