# Generated by Django 5.2.8 on 2025-12-20 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_staff"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_ti_e3e728_idx",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="subscription_end",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="subscription_start",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_tier",
        ),
    ]
