# Generated by Django 5.2.8 on 2025-12-20 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_migrate_subscription_data"),
        ("users", "0005_remove_user_users_user_ti_e3e728_idx_and_more"),
    ]

    operations = []
