# Generated by Django 5.2.8 on 2025-12-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_merge_20251220_2304"),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150)),
                ("mobile", models.CharField(max_length=20)),
                ("query", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Queries",
                "db_table": "queries",
                "ordering": ["-created_at"],
            },
        ),
    ]
