# Generated by Django 4.2.7 on 2025-12-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                    ("timeout", "Timeout"),
                ],
                default="ongoing",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="core.user",
            ),
        ),
    ]
